name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      deployto:
        required: true
        default: 'Test'
        description: "Choose environment to deploy to"
        type: choice
        options:
        - Test
        - Acceptance
        - Production
        
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deployto }}
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! ${{vars.ENV_CONTEXT_VAR}} api ${{secrets.API_KEY}}"
        env:
          First_Name: Mona
      - name: "show env vars"
        run: env
        
